### ISSUE TITLE
Salesforce record does not get created/updated, but drops of the delayed job list without any error

### ISSUE THREAD

**Issue by gsnavin** [InfoTech/salesforce_ar_sync#14]
Hi @bbotting 
I am looking into an issue where an salesforce record that gets inserted into the delayed job table gets deleted without being created/updated. I am not sure what the issue is, can you please help with it?

Thanks for the help.

Naveen

**Comment by bbotting** [comment]
Thanks for your interest in SalesforceArSync. While we do not actively assist in issue identification, we will certainly address any particular issues that you encounter in the Gem.

I am going to close this issue, but please feel free to open one with details of your findings.
