### ISSUE TITLE
SalesForce - ROR integration InvalidAuthenticityToken 

### ISSUE THREAD

**Issue by rahulgoutham** [InfoTech/salesforce_ar_sync#15]
I'm new to Rails-SalesForce integration. 
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)

How to generate and send AuthenticityToken from SalesForce to Rails app.

**Comment by lnediger** [comment]
https://github.com/InfoTech/salesforce_ar_sync/pull/13 This branch addresses the issue by explicitely setting the request forgery protection to respond with a null session. You can use this branch until this change is merged to master.

**Comment by rahulgoutham** [comment]
Thank you. lnediger Fixed.
