### ISSUE TITLE
Sales force to local DB sync did not happen

### ISSUE THREAD

**Issue by bhaskar-murabaha** [InfoTech/salesforce_ar_sync#17]
Hi, 
I am working on a project where this gem is integrated.. As the gem is already integrated it is working(syncing with SalesForce Db and staging DB as the app is hosted). But for bug fixing I can't work on staging/production environment directly. So I need a way when I am working with the application in my local I need SalesForce to sync with my local DB(as my app is able to send data to SalesForce).

So, How to make salesforce to sync with my local DB ?

**Comment by lnediger** [comment]
Services like [ForwardHQ](https://forwardhq.com) or [ngrok](http://ngrok.com) will create tunnels so that you can accept connections on your local development machine.
